### ISSUE TITLE
Private repositories do not work well

### ISSUE THREAD

**Issue by ktakiz** [chilicuil/tundle#5]
The followings are acceptable format. But they do not work with current version.
```
setenv -g @bundle 'user@server:dir/project.git'
setenv -g @bundle 'user@server:dir/project.git:master'
setenv -g @bundle 'ssh://user@server/dir/project.git'
setenv -g @bundle 'ssh://user@server/dir/project.git:master'
```

**Comment by javier-lopez** [comment]
Indeed, that seems to be the case @ktakiz, never required such usercase, I've seen you've implemented the required changes to allow private repositories, would you mind creating a PR so other users can benefit?

**Comment by ktakiz** [comment]
Thank you for considering that. I only looked at the install part, I hope it will work entirely.
